# Generated by Django 5.0 on 2023-12-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App', '0002_delete_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('f_nac', models.DateField(null=True)),
                ('f_registro', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
